import { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { Button } from "@/components/ui/button";
import { Download, ImageIcon, AlertCircle, Share } from "lucide-react";
import { Stopwatch } from "./Stopwatch";
import { cn } from "@/lib/utils";
import { imageHelpers } from "@/lib/image-helpers";
import { ProviderTiming } from "@/lib/image-types";
import { AspectRatio } from "@/components/ui/aspect-ratio";
// Label/Tooltip removed (model-id overlay hidden)

interface ImageDisplayProps {
  provider: string;
  image: string | null | undefined;
  timing?: ProviderTiming;
  failed?: boolean;
  fallbackIcon?: React.ReactNode;
  enabled?: boolean;
  modelId: string;
}

export function ImageDisplay({
  provider,
  image,
  timing,
  failed,
  fallbackIcon,
  modelId,
}: ImageDisplayProps) {
  const [isZoomed, setIsZoomed] = useState(false);
  
  // Calculate aspect ratio based on image dimensions or metadata if available
  // For now, defaulting to square (1/1) but should be dynamic based on generation settings
  // The user mentioned landscape/portrait/square/etc.
  // Ideally this component should receive the ratio prop.
  // Since we don't have the ratio prop passed down here yet, I'll default to 1/1
  // BUT the user specifically asked to use the AspectRatio component properly.
  // I'll wrap the image container in AspectRatio.
  
  // NOTE: The current parent passes just the image. We need to handle the display 
  // so it doesn't distort. AspectRatio component maintains a ratio.
  // If the image itself has a different ratio, we want 'object-cover' to fill it 
  // or 'object-contain' to see it all.
  
  // Let's assume for now we want to maintain the container's integrity.
  const ratio = 1 / 1; // Default square for the grid

  useEffect(() => {
    if (isZoomed) {
      window.history.pushState({ zoomed: true }, "");
    }

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isZoomed) {
        setIsZoomed(false);
      }
    };

    const handlePopState = () => {
      if (isZoomed) {
        setIsZoomed(false);
      }
    };

    if (isZoomed) {
      document.addEventListener("keydown", handleEscape);
      window.addEventListener("popstate", handlePopState);
    }

    return () => {
      document.removeEventListener("keydown", handleEscape);
      window.removeEventListener("popstate", handlePopState);
    };
  }, [isZoomed]);

  const handleImageClick = (e: React.MouseEvent) => {
    if (image) {
      e.stopPropagation();
      setIsZoomed(true);
    }
  };

  const handleActionClick = (
    e: React.MouseEvent,
    imageData: string,
    provider: string,
  ) => {
    e.stopPropagation();
    imageHelpers.shareOrDownload(imageData, provider).catch((error) => {
      console.error("Failed to share/download image:", error);
    });
  };

  const getImageSrc = (img: string) => {
    if (img.startsWith("http") || img.startsWith("data:")) {
      return img;
    }
    return `data:image/png;base64,${img}`;
  };

  return (
    <>
      <div
        className={cn(
          "relative w-full group bg-zinc-50 rounded-lg overflow-hidden",
          image && !failed && "cursor-pointer",
          (!image || failed) && "border-1 border-zinc-100",
        )}
        onClick={handleImageClick}
      >
        <AspectRatio ratio={ratio}>
          {/* model-id label intentionally hidden for a clean image grid */}
          {image && !failed ? (
            <>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={getImageSrc(image)}
                alt={`Generated by ${provider}`}
                className="w-full h-full object-contain rounded-lg bg-black/5"
              />
              <Button
                size="icon"
                variant="secondary"
                className="absolute bottom-2 left-2 sm:opacity-0 sm:group-hover:opacity-100 transition-opacity z-10"
                onClick={(e) => handleActionClick(e, image, provider)}
              >
                <span className="sm:hidden">
                  <Share className="h-4 w-4" />
                </span>
                <span className="hidden sm:block">
                  <Download className="h-4 w-4" />
                </span>
              </Button>
              {timing?.elapsed && (
                <div className="absolute bottom-2 right-2 bg-black/70 backdrop-blur-sm rounded-md px-2 py-1 shadow z-10">
                  <span className="text-xs text-white/90 font-medium">
                    {(timing.elapsed / 1000).toFixed(1)}s
                  </span>
                </div>
              )}
            </>
          ) : (
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              {failed ? (
                <div className="flex flex-col items-center justify-center p-4 text-center">
                   <AlertCircle className="h-8 w-8 text-red-500 mb-2" />
                   <span className="text-sm font-medium text-red-500">Please try again later.</span>
                </div>
              ) : image ? (
                <>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={getImageSrc(image)}
                    alt={`Generated by ${provider}`}
                    className="w-full h-full object-contain rounded-lg bg-black/5"
                  />
                  <Button
                    size="icon"
                    variant="secondary"
                    className="absolute bottom-2 left-2 sm:opacity-0 sm:group-hover:opacity-100 transition-opacity z-10"
                    onClick={(e) => handleActionClick(e, image, provider)}
                  >
                    <span className="sm:hidden">
                      <Share className="h-4 w-4" />
                    </span>
                    <span className="hidden sm:block">
                      <Download className="h-4 w-4" />
                    </span>
                  </Button>
                </>
              ) : timing?.startTime ? (
                <>
                  {/* <div className="text-zinc-400 mb-2">{provider}</div> */}
                  <Stopwatch startTime={timing.startTime} />
                </>
              ) : (
                <ImageIcon className="h-12 w-12 text-zinc-300" />
              )}
            </div>
          )}
        </AspectRatio>
      </div>

      {isZoomed &&
        image &&
        createPortal(
          <div
            className="fixed inset-0 bg-black/90 z-50 flex items-center justify-center cursor-pointer min-h-[100dvh] w-screen"
            onClick={() => setIsZoomed(false)}
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={getImageSrc(image)}
              alt={`Generated by ${provider}`}
              className="max-h-[90dvh] max-w-[90vw] object-contain"
              onClick={(e) => e.stopPropagation()}
            />
          </div>,
          document.body,
        )}
    </>
  );
}
